version: "3.5"
services:
  get_and_build:
    image: getBuild:latest
    build: .
    environment:
      - GIT_URL=${GIT_URL}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - PUSH_TO_DOCKER=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock