version: "3.5"
services:
  get_and_build:
    image: builder:latest
    build: .
    environment:
      - DOCKER_USERNAME=username
      - DOCKER_PASSWORD=password
      - GIT_URL=url
      - CONTAINER_NAME=container_name
      - PUSH_TO_DOCKER=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock