name: ex_3_2

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ex_3.2
    steps:
      - uses: actions/checkout@v2
      - name: Dockerfile
        run: docker build -t frontend .
      - name: Tags
        run: docker tag frontend registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Push
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web